### PR TITLE
Revised Nest function and type names

### LINKED ISSUE #122: Passing Error object directly to HttpException is deprecated (NestJS)
Passing the Zod validation error directly to the `BadRequestException` constructor is now triggering this warning

`DEPRECATED! Passing the error cause as the first argument to HttpException constructor is deprecated. You should use the "options" parameter instead: new HttpException("message", 400, { cause: new Error("Some Error") })`

### PR DESCRIPTION
**Pull request by Gabrola**
I've renamed some of the Nest function and type names as they have confused some people.

I've also changed how the types are consumed rather than using the `{} as T` hack. In my opinion, this makes it clearer that we are providing types rather than running any significant code at runtime.

Also updated the docs to better explain the role of every function and decorator, and how the type safety is done.
 
Also fixes #122

### CODE REVIEW

File: libs/ts-rest/nest/src/lib/ts-rest-nest.ts [hunk 1]
```diff
@@ -1,33 +1,48 @@
...
+type NestControllerShapeFromAppRouter<T extends AppRouter> = Without<
   AppRouterControllerShape<T>,
   AppRouter
 >;
 
-export type NestAppRouteShape<T extends AppRouter> = AppRouteShape<T>;
+type NestAppRouteShape<T extends AppRouter> = AppRouterRequestShapes<T>;
 
+/**
+ * @deprecated Use `nestControllerContract`, `NestControllerInterface`, `NestRequestShapes`, and `NestResponseShapes` instead. Check the docs for more info.
```
Comment (oliverbutler) [inline libs/ts-rest/nest/src/lib/ts-rest-nest.ts:44]: Can we link to the nest docs to save users some time?

**Comment by oliverbutler** [comment]
I want to pull this and play with it locally, but this looks great! 

I wonder if this is an opportunity to discuss adding codemods for migrations in ts-rest? I've never done them myself so not sure on the effort required on our side to make them.

File: libs/ts-rest/nest/src/lib/ts-rest-nest.ts (hunk 1 above)
Comment (Gabrola) [reply libs/ts-rest/nest/src/lib/ts-rest-nest.ts]: Absolutely!

**Comment by Gabrola** [comment]
> I want to pull this and play with it locally, but this looks great!
> 
> I wonder if this is an opportunity to discuss adding codemods for migrations in ts-rest? I've never done them myself so not sure on the effort required on our side to make them.

I've thought about it too. I think it could be a good idea to do during the next major release if we decide to drop the deprecated versions.

File: .changeset/dull-maps-draw.md [hunk 2]
```diff
@@ -0,0 +1,8 @@
+---
+'@ts-rest/nest': minor
+'@ts-rest/core': patch
+---
+
+Rename some Nest functions and types, and deprecate old names
```
Comment (michaelangrivera) [inline .changeset/dull-maps-draw.md:6]: Since we're renaming, should we indicate breaking changes in the release notes?

File: apps/docs/docs/core/form-data.mdx [hunk 3]
```diff
@@ -112,11 +112,11 @@ With Nest this is a pretty simple implementation, due to the extensible Decorato
 ```ts
 // nest
 @Controller()
-export class AppController implements ControllerShape {
+export class AppController implements NestControllerInterface<typeof c> {
   @Api(s.route.updateUserAvatar)
   @UseInterceptors(FileInterceptor('avatar'))
   async updateUserAvatar(
-    @ApiDecorator() { params: { id } }: RouteShape['updateUserAvatar'],
+    @TypedRequest() { params: { id } }: RequestShapes['updateUserAvatar'],
```
Comment (michaelangrivera) [inline apps/docs/docs/core/form-data.mdx:119]: I'm wondering if `TypedRequest` should just be named something to reflect the package name itself? 

For instance, importing `{ z } from 'zod'` feels super natural. So maybe something like, `TSRest` or `TSRestRoute` would look even better and allow people to easily distinguish when they're using the `ts-rest` library?

Comment (michaelangrivera) [reply apps/docs/docs/core/form-data.mdx:119]: So we would have:

```
import { TSRestRequest } from 'ts-rest/nest'

 async updateUserAvatar(
    @TSRestRequest() { params: { id } }: TSRestShapes['updateUserAvatar'],
```

File: apps/docs/docs/nest.md [hunk 4]
```diff
@@ -36,63 +50,61 @@ To handle JSON query parameters, you can use the `@JsonQuery()` decorator on eit
...
 
-## Response Return Type Safety
-
-You have two options to ensure HTTP type safety on your Nest Controllers:
-
-- `ControllerShape` as shown above:
-  - Your controller can implement the `ControllerShape` derived from `typeof s.controllerShape`
-  - This ensures your controller methods also align with the base interface shapes
-- `ResponseShapes`:
+## Explicit Response Type Safety
```
Comment (michaelangrivera) [inline apps/docs/docs/nest.md:72]: Love this.

File: libs/ts-rest/nest/src/lib/ts-rest-nest.ts [hunk 5]
```diff
@@ -1,33 +1,49 @@
...
+  never
+>;
 
-export type NestControllerShapeFromAppRouter<T extends AppRouter> = Without<
+type NestControllerShapeFromAppRouter<T extends AppRouter> = Without<
   AppRouterControllerShape<T>,
   AppRouter
 >;
 
-export type NestAppRouteShape<T extends AppRouter> = AppRouteShape<T>;
```
Comment (michaelangrivera) [inline libs/ts-rest/nest/src/lib/ts-rest-nest.ts:29]: We should communicate we are removing this from exports. If people are using this (somehow), that's a breaking change.

File: libs/ts-rest/nest/src/lib/ts-rest.interceptor.ts [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+  SetMetadata,
+  UseInterceptors,
+} from '@nestjs/common';
+import { map, Observable } from 'rxjs';
+import { Response } from 'express-serve-static-core';
+import { AppRoute } from '@ts-rest/core';
+import { tsRestAppRouteMetadataKey } from './typed-request.decorator';
+
+@Injectable()
+export class TsRestInterceptor implements NestInterceptor {
```
Comment (michaelangrivera) [inline libs/ts-rest/nest/src/lib/ts-rest.interceptor.ts:21]: Exactly what I was saying, `TsRestInterceptor` makes me _know_ that I'm using ts-rest. I love this personally.

File: .changeset/dull-maps-draw.md (hunk 2 above)
Comment (Gabrola) [reply .changeset/dull-maps-draw.md:6]: We're still keeping the old names, but marking them as deprecated so it's technically not a breaking change yet

Comment (michaelangrivera) [reply .changeset/dull-maps-draw.md:6]: AH missed that, thanks!

File: apps/docs/docs/core/form-data.mdx (hunk 3 above)
Comment (Gabrola) [reply apps/docs/docs/core/form-data.mdx:119]: I agree fully. That was actually the initial name I came up with, but I felt like `TSRestRequest` was a little clunky to type and a bit of tongue-twister 😅

Let's think of something

File: libs/ts-rest/nest/src/lib/ts-rest-nest.ts (hunk 5 above)
Comment (Gabrola) [reply libs/ts-rest/nest/src/lib/ts-rest-nest.ts:29]: I believe this was an unintended export, as it was never meant to be used directly. I'm going back to @oliverbutler's comment on avoiding breaking changes the second we document our API (which we did but not too long ago, I doubt anyone picked this one up specifically from the docs yet 😅).

I'm personally fine with the trade-off of potentially breaking some code using undocumented features for the purpose of keeping our code more maintainable. Especially since this specific example would be very easy to fix.

I guess, rather than bumping the major version for such a small change, we could at least add it to the release notes, in case this affects some people.

Comment (michaelangrivera) [reply libs/ts-rest/nest/src/lib/ts-rest-nest.ts:29]: Yup, that was my point, let's at a minimum, add it to the release notes.

File: .changeset/dull-maps-draw.md [hunk 7]
```diff
@@ -0,0 +1,8 @@
...
+
+Fix Nest deprecation warning when passing Zod error to HttpException (#122)
```
Comment (michaelangrivera) [inline .changeset/dull-maps-draw.md:8]: Should we add the removal of the exports here? 

Or does that go somewhere else?

**Review by michaelangrivera — APPROVED** [review]
LGTM! Will re-approve should you add anything to changeset

File: .changeset/dull-maps-draw.md (hunk 7 above)
Comment (Gabrola) [reply .changeset/dull-maps-draw.md:8]: Yup, here sounds about right in this case

**Review by oliverbutler — APPROVED** [review]

**Comment by oliverbutler** [comment]
This looks great! LGTM :)

**Comment by oliverbutler** [comment]
I way prefer the naming, and awesome that you polled the discord 🔥
